### ISSUE TITLE
TLS password leak

### ISSUE THREAD

**Issue by vroyer** [datastax/pulsar#48]
**Describe the bug**
When TLS is enabled, a TLS keystore password leak in the command line.

**Expected behavior**
Should not leak passwords

**Comment by vroyer** [comment]
<img width="1792" alt="Screenshot 2022-03-21 at 14 23 05" src="https://user-images.githubusercontent.com/10274713/159926110-af16b2d6-333e-4d21-b347-cc1814500cec.png">

**Comment by michaeljmarshall** [comment]
@vroyer - I am going to close this issue, as it is superseded by https://github.com/datastax/pulsar-helm-chart/issues/164. Note that we just released our Luna Streaming release with the 3.8.0 zookeeper fix described here https://issues.apache.org/jira/browse/ZOOKEEPER-4396. Unless I am mistaken, anyone deploying this version of Pulsar without Helm can provide secrets by file via the command to start pulsar.
